import db from './index.js';
import crypto from 'crypto';

const seedVideos = [
  {
    fileName: 'Nakie_Hammock_Beach_Sunset_B-Roll.mp4',
    description: 'A couple relaxes in a Nakie recycled hammock strung between two palm trees at golden hour. Waves crash gently in the background as the camera slowly pans across the scene, capturing the warm sunset tones reflecting off the hammock fabric.',
    products: ['Hammock'],
    sceneBackground: 'Beach',
    shotType: 'b-roll',
    audioType: 'ambient',
    groupType: 'Couple',
    groupCount: 2,
    hasLogo: true,
    duration: 45,
    sizeBytes: 128_000_000,
  },
  {
    fileName: 'Family_Camping_Puffy_Blanket_Review.mp4',
    description: 'A family of four unpacks and tests the Nakie Puffy Blanket at their campsite. The kids wrap themselves up while the parents demonstrate the compact packing size. Great testimonial content with authentic reactions.',
    products: ['Puffy Blanket'],
    sceneBackground: 'Campsite',
    shotType: 'talking head',
    audioType: 'voiceover',
    groupType: 'Family',
    groupCount: 4,
    hasLogo: true,
    duration: 182,
    sizeBytes: 456_000_000,
  },
  {
    fileName: 'Solo_Hiker_Mountains_Hammock_Setup.mp4',
    description: 'A solo hiker reaches a mountain summit and sets up a Nakie travel hammock between two trees overlooking a valley. Time-lapse clouds roll through as they relax with a book, showcasing the hammock in an epic alpine setting.',
    products: ['Hammock', 'Backpack'],
    sceneBackground: 'Mountains',
    shotType: 'b-roll',
    audioType: 'music',
    groupType: 'Solo',
    groupCount: 1,
    hasLogo: false,
    duration: 62,
    sizeBytes: 195_000_000,
  },
  {
    fileName: 'UGC_Beach_Hammock_Compilation.mp4',
    description: 'User-generated content compilation featuring multiple customers enjoying their Nakie hammocks at various beaches across Australia. Quick cuts between different setups, sunny vibes, and happy customers waving at the camera.',
    products: ['Hammock'],
    sceneBackground: 'Beach',
    shotType: 'UGC compilation',
    audioType: 'music',
    groupType: 'Friends',
    groupCount: 6,
    hasLogo: true,
    duration: 120,
    sizeBytes: 340_000_000,
  },
  {
    fileName: 'Product_Demo_Sand_Free_Towel.mp4',
    description: 'Close-up product demonstration of the Nakie sand-free towel. Sand is poured onto the towel and slides right off. Comparison with regular towel shows the difference. Clean studio lighting with brand colors in the background.',
    products: ['Sand-Free Towel'],
    sceneBackground: 'Studio',
    shotType: 'product demo',
    audioType: 'voiceover',
    groupType: 'Solo',
    groupCount: 1,
    hasLogo: true,
    duration: 90,
    sizeBytes: 220_000_000,
  },
  {
    fileName: 'Golden_Hour_Picnic_Puffy_Blanket.mp4',
    description: 'Three friends enjoy a golden hour picnic on a Nakie Puffy Blanket in a wildflower meadow. Cheese board, wine, and laughter as the warm light wraps around them. Beautiful lifestyle content perfect for social media.',
    products: ['Puffy Blanket'],
    sceneBackground: 'Meadow',
    shotType: 'b-roll',
    audioType: 'ambient',
    groupType: 'Friends',
    groupCount: 3,
    hasLogo: false,
    duration: 55,
    sizeBytes: 175_000_000,
  },
  {
    fileName: 'Talking_Head_Sustainability_Story.mp4',
    description: 'Nakie founder speaks to camera about the brand sustainability mission, explaining how hammocks are made from recycled plastic bottles. Office setting with product samples visible on shelves behind. Passionate and authentic delivery.',
    products: ['Hammock', 'Puffy Blanket', 'Sand-Free Towel'],
    sceneBackground: 'Indoor',
    shotType: 'talking head',
    audioType: 'dialogue',
    groupType: 'Solo',
    groupCount: 1,
    hasLogo: true,
    duration: 240,
    sizeBytes: 580_000_000,
  },
  {
    fileName: 'Drone_Beach_Aerial_Hammock.mp4',
    description: 'Stunning drone footage flying over a pristine beach where a colorful Nakie hammock is set up between driftwood. Camera pulls back to reveal the full coastline. Turquoise water and white sand create a paradise backdrop.',
    products: ['Hammock'],
    sceneBackground: 'Beach',
    shotType: 'aerial',
    audioType: 'music',
    groupType: 'Solo',
    groupCount: 1,
    hasLogo: false,
    duration: 35,
    sizeBytes: 290_000_000,
  },
  {
    fileName: 'Backpack_Hiking_Trail_Review.mp4',
    description: 'An outdoor enthusiast reviews the Nakie recycled backpack on a coastal hiking trail. Shows all compartments, demonstrates capacity, and tests comfort over a 5km hike. Genuine review with pros and cons discussed.',
    products: ['Backpack'],
    sceneBackground: 'Trail',
    shotType: 'talking head',
    audioType: 'voiceover',
    groupType: 'Solo',
    groupCount: 1,
    hasLogo: true,
    duration: 310,
    sizeBytes: 720_000_000,
  },
  {
    fileName: 'Festival_Friends_Hammock_Party.mp4',
    description: 'A group of friends set up multiple Nakie hammocks at a music festival campsite. Colorful fairy lights strung between trees, everyone lounging and chatting. Captures the social, fun energy of the brand perfectly.',
    products: ['Hammock'],
    sceneBackground: 'Festival',
    shotType: 'b-roll',
    audioType: 'ambient',
    groupType: 'Friends',
    groupCount: 5,
    hasLogo: true,
    duration: 78,
    sizeBytes: 230_000_000,
  },
  {
    fileName: 'Rainforest_Hammock_Morning_Routine.mp4',
    description: 'A woman wakes up in a Nakie hammock deep in a tropical rainforest. Morning mist, bird sounds, and dappled sunlight create an ethereal atmosphere. She stretches, makes coffee on a camp stove, and reads a book.',
    products: ['Hammock'],
    sceneBackground: 'Forest',
    shotType: 'b-roll',
    audioType: 'ambient',
    groupType: 'Solo',
    groupCount: 1,
    hasLogo: false,
    duration: 95,
    sizeBytes: 310_000_000,
  },
  {
    fileName: 'Puffy_Blanket_Stargazing_Night.mp4',
    description: 'Time-lapse of stars wheeling overhead while a couple lies on a Nakie Puffy Blanket in an open field. Occasional shooting star. The blanket keeps them warm as temperatures drop. Cinematic and aspirational nightscape content.',
    products: ['Puffy Blanket'],
    sceneBackground: 'Outdoor Night',
    shotType: 'b-roll',
    audioType: 'music',
    groupType: 'Couple',
    groupCount: 2,
    hasLogo: false,
    duration: 42,
    sizeBytes: 188_000_000,
  },
  {
    fileName: 'Sand_Free_Towel_Beach_Day_UGC.mp4',
    description: 'UGC video from a customer showing their beach day with the Nakie sand-free towel. Kids playing, towel staying clean, easy shake-off at the end. Real family content that resonates with parents who hate sandy towels.',
    products: ['Sand-Free Towel'],
    sceneBackground: 'Beach',
    shotType: 'UGC compilation',
    audioType: 'dialogue',
    groupType: 'Family',
    groupCount: 3,
    hasLogo: false,
    duration: 68,
    sizeBytes: 165_000_000,
  },
  {
    fileName: 'Product_Launch_Teaser_New_Colors.mp4',
    description: 'Quick-cut teaser video showcasing new seasonal hammock colors. Close-up fabric shots transition with swooping camera moves. Bold typography overlays announce the collection. High energy, social-media-ready format.',
    products: ['Hammock'],
    sceneBackground: 'Studio',
    shotType: 'product demo',
    audioType: 'music',
    groupType: 'Solo',
    groupCount: 0,
    hasLogo: true,
    duration: 30,
    sizeBytes: 95_000_000,
  },
  {
    fileName: 'Yoga_Beach_Puffy_Blanket_Session.mp4',
    description: 'A yoga instructor leads a morning session on a Nakie Puffy Blanket spread on the beach. Smooth, flowing movements with waves as a backdrop. The blanket provides cushioning on the sand. Peaceful and mindful content.',
    products: ['Puffy Blanket'],
    sceneBackground: 'Beach',
    shotType: 'b-roll',
    audioType: 'music',
    groupType: 'Solo',
    groupCount: 1,
    hasLogo: true,
    duration: 150,
    sizeBytes: 410_000_000,
  },
  {
    fileName: 'Van_Life_Hammock_Setup_Tutorial.mp4',
    description: 'A van lifer shows how they incorporate the Nakie hammock into their travel setup. Demonstrating attachment points on the van, setting up at different campsites, and packing away. Practical tips and tricks included.',
    products: ['Hammock', 'Puffy Blanket'],
    sceneBackground: 'Campsite',
    shotType: 'talking head',
    audioType: 'voiceover',
    groupType: 'Couple',
    groupCount: 2,
    hasLogo: true,
    duration: 275,
    sizeBytes: 650_000_000,
  },
  {
    fileName: 'River_Swimming_Towel_Adventure.mp4',
    description: 'Group of friends hiking to a hidden river swimming hole. They lay out Nakie sand-free towels on the rocks, swim in crystal clear water, and dry off quickly. Adventure lifestyle content with high production value.',
    products: ['Sand-Free Towel'],
    sceneBackground: 'River',
    shotType: 'b-roll',
    audioType: 'music',
    groupType: 'Friends',
    groupCount: 4,
    hasLogo: false,
    duration: 88,
    sizeBytes: 275_000_000,
  },
  {
    fileName: 'Unboxing_Full_Nakie_Collection.mp4',
    description: 'Influencer unboxes the complete Nakie product collection including hammock, puffy blanket, sand-free towel, and backpack. Each item is shown in detail with genuine first impressions. Clean desk setup with ring light.',
    products: ['Hammock', 'Puffy Blanket', 'Sand-Free Towel', 'Backpack'],
    sceneBackground: 'Indoor',
    shotType: 'talking head',
    audioType: 'dialogue',
    groupType: 'Solo',
    groupCount: 1,
    hasLogo: true,
    duration: 420,
    sizeBytes: 980_000_000,
  },
  {
    fileName: 'Sunset_Cliff_Hammock_Timelapse.mp4',
    description: 'Breathtaking timelapse of a sunset from a cliff edge with a Nakie hammock in the foreground. Colors shift from golden to deep orange to purple as the sun dips below the horizon. The hammock gently sways in the breeze.',
    products: ['Hammock'],
    sceneBackground: 'Mountains',
    shotType: 'b-roll',
    audioType: 'ambient',
    groupType: 'Solo',
    groupCount: 0,
    hasLogo: false,
    duration: 28,
    sizeBytes: 142_000_000,
  },
  {
    fileName: 'Kids_Backyard_Hammock_Fun.mp4',
    description: 'Two kids playing on a Nakie hammock in the backyard, swinging and giggling. Parents supervise nearby on a puffy blanket. Wholesome family content that shows the product is sturdy enough for active kids.',
    products: ['Hammock', 'Puffy Blanket'],
    sceneBackground: 'Backyard',
    shotType: 'b-roll',
    audioType: 'ambient',
    groupType: 'Family',
    groupCount: 4,
    hasLogo: true,
    duration: 58,
    sizeBytes: 168_000_000,
  },
  {
    fileName: 'Behind_The_Scenes_Photoshoot.mp4',
    description: 'Behind-the-scenes footage from a Nakie brand photoshoot. Models pose with products on location at Byron Bay. Quick glimpses of the creative team at work, lighting setups, and final shots being composed.',
    products: ['Hammock', 'Sand-Free Towel'],
    sceneBackground: 'Beach',
    shotType: 'b-roll',
    audioType: 'music',
    groupType: 'Friends',
    groupCount: 8,
    hasLogo: true,
    duration: 110,
    sizeBytes: 380_000_000,
  },
  {
    fileName: 'Winter_Camping_Puffy_Blanket_Test.mp4',
    description: 'Testing the Nakie Puffy Blanket in cold winter conditions. Frost on the ground, breath visible in the air. Demonstrating warmth retention and water resistance. Honest review format with temperature readings shown on screen.',
    products: ['Puffy Blanket'],
    sceneBackground: 'Mountains',
    shotType: 'talking head',
    audioType: 'voiceover',
    groupType: 'Solo',
    groupCount: 1,
    hasLogo: true,
    duration: 195,
    sizeBytes: 490_000_000,
  },
  {
    fileName: 'Tropical_Island_Hammock_Paradise.mp4',
    description: 'Cinematic footage of a Nakie hammock on a tropical island. Crystal clear water, white sand, palm trees swaying. A woman reads a book while gently swinging. Luxury travel meets sustainable products. Perfect hero content.',
    products: ['Hammock'],
    sceneBackground: 'Beach',
    shotType: 'b-roll',
    audioType: 'music',
    groupType: 'Solo',
    groupCount: 1,
    hasLogo: true,
    duration: 72,
    sizeBytes: 350_000_000,
  },
  {
    fileName: 'Dog_Park_Sand_Free_Towel.mp4',
    description: 'A dog owner uses the Nakie sand-free towel to dry off their golden retriever after a swim at the dog park. The towel handles wet dog hair surprisingly well. Fun, relatable content that pet owners will love.',
    products: ['Sand-Free Towel'],
    sceneBackground: 'Park',
    shotType: 'UGC compilation',
    audioType: 'dialogue',
    groupType: 'Solo',
    groupCount: 1,
    hasLogo: false,
    duration: 45,
    sizeBytes: 112_000_000,
  },
];

export function seedDatabase() {
  const existing = db.prepare('SELECT COUNT(*) as count FROM videos').get() as { count: number };
  if (existing.count > 0) return;

  const insert = db.prepare(`
    INSERT INTO videos (id, drive_file_id, file_name, description, products, scene_background, shot_type, audio_type, group_type, group_count, has_logo, duration, size_bytes, thumbnail_url, drive_url, analyzed_at, created_at)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
  `);

  const insertMany = db.transaction((videos: typeof seedVideos) => {
    for (const v of videos) {
      const id = crypto.randomUUID();
      const driveFileId = `seed_${crypto.randomBytes(12).toString('hex')}`;
      const analyzedAt = new Date(Date.now() - Math.random() * 30 * 86400000).toISOString();
      const createdAt = new Date(Date.now() - Math.random() * 90 * 86400000).toISOString();

      insert.run(
        id,
        driveFileId,
        v.fileName,
        v.description,
        JSON.stringify(v.products),
        v.sceneBackground,
        v.shotType,
        v.audioType,
        v.groupType,
        v.groupCount,
        v.hasLogo ? 1 : 0,
        v.duration,
        v.sizeBytes,
        '', // thumbnailUrl - will be proxied via drive
        `https://drive.google.com/file/d/${driveFileId}/view`,
        analyzedAt,
        createdAt,
      );
    }
  });

  insertMany(seedVideos);
  console.log(`Seeded ${seedVideos.length} videos`);
}
